## YAML Template.
---
server:
  port: 9090
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mvd_dev?useSSL=false&characterEncoding=utf-8&useUnicode=true
    username: mvd
    password: mvd
